### ISSUE TITLE
download an album ?

### ISSUE THREAD

**Issue by poulenque** [frosas/spotify-to-mp3#19]
Hi, 
Is there a way to download albums ?
I tried this input file :

```
http://play.spotify.com/album/6k0WkUq4W9MIyUhSOVLoxX
```
but I got that : 
```
Resolving "http://open.spotify.com/album/6k0WkUq4W9MIyUhSOVLoxX"
Searching "http://open.spotify.com/album/6k0WkUq4W9MIyUhSOVLoxX" on Grooveshark
Track not found
```

I can't find any documentation on how to write the input file... that might be helpful :¬P

thanks !

great job though !

**Comment by dulakm** [comment]
Working on it, will be done in few days.

**Comment by pmdusso** [comment]
Is this working for linux? Maybe I should update before trying?

**Comment by dulakm** [comment]
I've developed and tried it on Fedora.
