### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by m93a** [frosas/spotify-to-mp3#43]
It would be fine to have a download progress logging.

**Comment by tomaszgieres** [comment]
Are you talking about download progress of a single song or about all the collection?
It would be easy to implement the second one. I'm not sure about the first but it's useless IMO as it usually takes a few seconds to get a single song.

**Comment by dulakm** [comment]
Working on it, will be done in few days.

**Comment by kenorb** [comment]
See pull #45.
