### ISSUE TITLE
 404 Resource Not Found (RestClient::ResourceNotFound)    Help?

### ISSUE THREAD

**Issue by mastovija** [frosas/spotify-to-mp3#52]
Every time I run spotify-to-mp3 show me this message

 /var/lib/gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!': 404 Resource Not Found (RestClient::ResourceNotFound)
	from /var/lib/gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
	from /var/lib/gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
	from /usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /var/lib/gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
	from /var/lib/gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /var/lib/gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /var/lib/gems/2.0.0/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
	from /var/lib/gems/2.0.0/gems/grooveshark-0.2.14/lib/grooveshark/client.rb:126:in `token_data'
	from /var/lib/gems/2.0.0/gems/grooveshark-0.2.14/lib/grooveshark/client.rb:11:in `initialize'
	from /var/lib/gems/2.0.0/gems/spotify-to-mp3-0.7.2/lib/spotify_to_mp3/dependency_container.rb:15:in `new'
	from /var/lib/gems/2.0.0/gems/spotify-to-mp3-0.7.2/lib/spotify_to_mp3/dependency_container.rb:15:in `grooveshark'
	from /var/lib/gems/2.0.0/gems/spotify-to-mp3-0.7.2/lib/spotify_to_mp3/dependency_container.rb:23:in `app'
	from /var/lib/gems/2.0.0/gems/spotify-to-mp3-0.7.2/bin/spotify-to-mp3:7:in `<top (required)>'
	from /usr/local/bin/spotify-to-mp3:23:in `load'
	from /usr/local/bin/spotify-to-mp3:23:in `<main>'

I followed the installations instructions as said. Any body knows something about that?

**Comment by martinbetz** [comment]
Grooveshark shut down. This gem used Grooveshark to source the music. Hence this gem is not working any longer.
